#!/usr/bin/env node

var builtins = require('builtins');

var cp = require('child_process');
var fs = require('fs');
var path = require('path');
var findRequires = require('find-requires');

var args = process.argv.slice(2);

var file = path.join(process.cwd(), args.shift());

var requires = findRequires(fs.readFileSync(file, 'utf-8'));

var npmModules = requires
                    .filter(function removeRelative(r) {
                        return r[0] !== '.' && r[0] !== '/';
                    })
                    .map(function removeSubdirs(r) {
                        return r.split('/')[0];
                    })
                    .filter(function removeBuiltins(item) {
                        return builtins.indexOf(item) === -1;
                    })
                    .filter((function removeDupes() {
                        var seen = {};
                        return function (item) {
                            if (!seen[item]) {
                                seen[item] = true;
                                return true;
                            }
                        };
                    })());

var spawnArgs = ['install'].concat(npmModules).concat(args);
cp.spawn('npm', spawnArgs, {
    stdio: 'inherit'
});
